[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
w_3_subs_tracker = "9ooN4bXynREMTKjaQ8ZfemrhCBe8a7xjscCXKVTUFpZg"

[programs.devnet]
w_3_subs_tracker = "9ooN4bXynREMTKjaQ8ZfemrhCBe8a7xjscCXKVTUFpZg"

[programs.mainnet]
w_3_subs_tracker = "9ooN4bXynREMTKjaQ8ZfemrhCBe8a7xjscCXKVTUFpZg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
mainStateInit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/mainState.ts"
